import { useState, useEffect } from 'react'
import { getConversationSummary, createTicketFromChat } from '../services/chatService'

/**
 * TicketFromChatModal
 * ────────────────────
 * Opens when a tech or customer wants to convert a chat conversation into a
 * support ticket.
 *
 * Props:
 *  - conversationId:  number   – the conversation to summarise
 *  - isOpen:          boolean
 *  - onClose:         () => void
 *  - onCreated:       (ticket: { ticketId, ticketNumber, subject }) => void
 */
export default function TicketFromChatModal({ conversationId, isOpen, onClose, onCreated }) {
  const [loading, setLoading]     = useState(false)
  const [creating, setCreating]   = useState(false)
  const [error, setError]         = useState(null)
  const [subject, setSubject]     = useState('')
  const [description, setDescription] = useState('')
  const [transcript, setTranscript]   = useState('')
  const [showTranscript, setShowTranscript] = useState(false)
  const [created, setCreated]     = useState(null)  // result after creation

  // Reset + load summary whenever modal opens
  useEffect(() => {
    if (!isOpen || !conversationId) return
    setError(null)
    setCreated(null)
    setSubject('')
    setDescription('')
    setTranscript('')
    setShowTranscript(false)
    setLoading(true)

    getConversationSummary(conversationId)
      .then(data => {
        setSubject(data.title || '')
        setDescription(data.description || '')
        setTranscript(data.transcript || '')
      })
      .catch(err => setError(err.message || 'Failed to generate summary'))
      .finally(() => setLoading(false))
  }, [isOpen, conversationId])

  const handleCreate = async () => {
    if (!subject.trim()) { setError('Subject is required.'); return }
    setCreating(true)
    setError(null)
    try {
      const result = await createTicketFromChat(conversationId, subject.trim(), description.trim())
      setCreated(result)
      onCreated?.(result)
    } catch (err) {
      setError(err.message || 'Failed to create ticket')
    } finally {
      setCreating(false)
    }
  }

  if (!isOpen) return null

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
      onClick={(e) => { if (e.target === e.currentTarget) onClose() }}
      role="dialog"
      aria-modal="true"
      aria-label="Create Ticket from Chat"
    >
      <div className="bg-gray-900 border border-gray-700 rounded-xl shadow-2xl w-full max-w-lg max-h-[90vh] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-700 flex-shrink-0">
          <div>
            <h2 className="text-base font-semibold text-white">🎫 Create Ticket from Chat</h2>
            <p className="text-xs text-gray-400 mt-0.5">
              Summary generated by AI · edit before submitting
            </p>
          </div>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-white transition-colors"
            aria-label="Close"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-5 py-4 space-y-4">
          {loading && (
            <div className="text-center text-gray-400 py-8 animate-pulse text-sm">
              ✨ Generating summary…
            </div>
          )}

          {!loading && created && (
            <div className="bg-emerald-900/30 border border-emerald-700 rounded-lg p-4 text-center">
              <p className="text-emerald-300 font-semibold text-lg">✅ Ticket Created!</p>
              <p className="text-emerald-400 mt-1">
                <span className="font-mono font-bold">{created.ticketNumber}</span>
              </p>
              <p className="text-gray-400 text-sm mt-2">{created.subject}</p>
              <p className="text-gray-500 text-xs mt-1">A technician will respond soon.</p>
            </div>
          )}

          {!loading && !created && (
            <>
              {error && (
                <div className="bg-red-900/30 border border-red-700 rounded-lg px-3 py-2 text-red-300 text-sm">
                  {error}
                </div>
              )}

              {/* Subject */}
              <div>
                <label className="block text-xs font-medium text-gray-400 mb-1">Subject *</label>
                <input
                  type="text"
                  value={subject}
                  onChange={e => setSubject(e.target.value)}
                  maxLength={200}
                  className="w-full bg-gray-800 border border-gray-600 focus:border-blue-500 text-white text-sm rounded-lg px-3 py-2 focus:outline-none transition-colors placeholder-gray-500"
                  placeholder="Brief description of the issue"
                />
              </div>

              {/* Description */}
              <div>
                <label className="block text-xs font-medium text-gray-400 mb-1">Description</label>
                <textarea
                  value={description}
                  onChange={e => setDescription(e.target.value)}
                  rows={5}
                  className="w-full bg-gray-800 border border-gray-600 focus:border-blue-500 text-white text-sm rounded-lg px-3 py-2 focus:outline-none transition-colors resize-y placeholder-gray-500"
                  placeholder="Detailed description of the problem"
                />
              </div>

              {/* Transcript toggle */}
              {transcript && (
                <div>
                  <button
                    type="button"
                    onClick={() => setShowTranscript(s => !s)}
                    className="text-xs text-blue-400 hover:text-blue-300 transition-colors"
                  >
                    {showTranscript ? '▼ Hide chat transcript' : '▶ Show full chat transcript'}
                  </button>
                  {showTranscript && (
                    <div className="mt-2 bg-gray-800/70 border border-gray-700 rounded-lg p-3 max-h-40 overflow-y-auto">
                      <pre className="text-[11px] text-gray-400 whitespace-pre-wrap font-mono leading-relaxed">
                        {transcript}
                      </pre>
                    </div>
                  )}
                </div>
              )}
            </>
          )}
        </div>

        {/* Footer */}
        <div className="px-5 py-4 border-t border-gray-700 flex justify-end gap-3 flex-shrink-0 bg-gray-900">
          {!created ? (
            <>
              <button
                onClick={onClose}
                className="px-4 py-2 text-sm text-gray-400 hover:text-white transition-colors rounded-lg hover:bg-gray-800"
              >
                Cancel
              </button>
              <button
                onClick={handleCreate}
                disabled={loading || creating || !subject.trim()}
                className="px-5 py-2 bg-blue-600 hover:bg-blue-500 text-white text-sm font-medium rounded-lg transition-colors disabled:opacity-50 disabled:bg-gray-700"
              >
                {creating ? '⏳ Creating…' : '🎫 Create Ticket'}
              </button>
            </>
          ) : (
            <button
              onClick={onClose}
              className="px-5 py-2 bg-emerald-700 hover:bg-emerald-600 text-white text-sm font-medium rounded-lg transition-colors"
            >
              Done
            </button>
          )}
        </div>
      </div>
    </div>
  )
}
