/**
 * chatQualityJob.js
 * =================
 * Automated weekly analysis job that runs every Monday at 02:00 AM.
 *
 * Responsibilities:
 *  1. Compute quality metrics for the previous week
 *  2. Identify top knowledge gaps (low-confidence + thumbs-down queries)
 *  3. Flag low-rated intents / responses
 *  4. Detect quality drift (thumbs-up rate below threshold)
 *  5. Persist a snapshot to chat_quality_snapshots
 *  6. Email a structured report to management
 *  7. Purge old PII-containing free-text (GDPR 90-day policy)
 */

import cron from 'node-cron';
import pool from '../config/database.js';

// Thumbs-up rate below this % triggers a quality-degradation alert
const QUALITY_ALERT_THRESHOLD = 70;

// ── Email helper (uses the existing mailer in the project) ────────────────────
async function sendQualityReport(reportData) {
  try {
    // Import emailService lazily to avoid circular deps
    const { sendEmail } = await import('./emailService.js').catch(() => ({ sendEmail: null }));
    if (!sendEmail) {
      console.log('📧 [ChatQualityJob] Email service not available — skipping email');
      return;
    }

    // Fetch management + admin emails
    const result = await pool.query(
      `SELECT email, first_name FROM users
       WHERE role IN ('management', 'admin') AND is_active = true`
    );
    if (!result.rows.length) return;

    const { weekStart, weekEnd, metrics, topGaps, lowRatedIntents, alerts } = reportData;

    const alertSection = alerts.length > 0
      ? `<div style="border-left:4px solid #ef4444;padding:8px 16px;margin:16px 0;background:#fef2f2">
           <b>⚠️ Alerts:</b><br>${alerts.join('<br>')}
         </div>`
      : '';

    const gapRows = topGaps.slice(0, 10).map(g =>
      `<tr>
         <td style="padding:4px 8px">${g.query_text?.slice(0, 80)}</td>
         <td style="padding:4px 8px;text-align:center">${g.occurrence_count}</td>
         <td style="padding:4px 8px;text-align:center">${g.thumbs_down_count}</td>
       </tr>`
    ).join('');

    const intentRows = lowRatedIntents.slice(0, 10).map(i =>
      `<tr>
         <td style="padding:4px 8px">${i.failure_reason || 'unknown'}</td>
         <td style="padding:4px 8px;text-align:center">${i.count}</td>
       </tr>`
    ).join('');

    const html = `
      <div style="font-family:sans-serif;max-width:600px">
        <h2 style="color:#1d4ed8">📊 BlueClue Chatbot — Weekly Quality Report</h2>
        <p style="color:#6b7280">${weekStart} → ${weekEnd}</p>
        ${alertSection}
        <h3>Overview</h3>
        <table style="width:100%;border-collapse:collapse">
          <tr><td>Total conversations</td><td><b>${metrics.totalConversations}</b></td></tr>
          <tr><td>Thumbs-up rate</td><td><b>${metrics.thumbsUpRate}%</b></td></tr>
          <tr><td>Avg star rating</td><td><b>${metrics.avgStarRating ?? '—'} / 5</b></td></tr>
          <tr><td>NPS score</td><td><b>${metrics.npsScore ?? '—'}</b></td></tr>
          <tr><td>Problem solved rate</td><td><b>${metrics.solvedRate ?? '—'}%</b></td></tr>
          <tr><td>Ticket deflection rate</td><td><b>${metrics.deflectionRate}%</b></td></tr>
        </table>

        <h3>🕳️ Top Unanswered / Low-Quality Questions</h3>
        <p style="color:#6b7280">Create KB articles to address these gaps.</p>
        <table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb">
          <tr style="background:#f3f4f6">
            <th style="padding:4px 8px;text-align:left">Query</th>
            <th style="padding:4px 8px">Occurrences</th>
            <th style="padding:4px 8px">👎</th>
          </tr>
          ${gapRows || '<tr><td colspan="3" style="padding:8px;color:#6b7280">None this week 🎉</td></tr>'}
        </table>

        <h3>📉 Most Common Negative Feedback Reasons</h3>
        <table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb">
          <tr style="background:#f3f4f6">
            <th style="padding:4px 8px;text-align:left">Reason</th>
            <th style="padding:4px 8px">Count</th>
          </tr>
          ${intentRows || '<tr><td colspan="2" style="padding:8px;color:#6b7280">No negative feedback this week 🎉</td></tr>'}
        </table>

        <p style="color:#9ca3af;font-size:12px;margin-top:24px">
          Auto-generated by the BlueClue analytics engine. Do not reply to this email.
        </p>
      </div>
    `;

    for (const { email, first_name } of result.rows) {
      await sendEmail({
        to: email,
        subject: `[BlueClue] Weekly Chatbot Quality Report — ${weekStart}`,
        html,
      }).catch(err => console.warn(`📧 Failed to email ${email}:`, err.message));
    }

    console.log(`📧 [ChatQualityJob] Report emailed to ${result.rows.length} manager(s)`);
  } catch (err) {
    console.error('[ChatQualityJob] Email failed:', err.message);
  }
}

// ── Core analysis function ────────────────────────────────────────────────────
async function runWeeklyAnalysis() {
  const startTime = Date.now();
  console.log('📊 [ChatQualityJob] Starting weekly analysis...');

  try {
    const weekEnd   = new Date();
    const weekStart = new Date(weekEnd);
    weekStart.setDate(weekStart.getDate() - 7);

    const fmtDate = d => d.toISOString().slice(0, 10);

    const [
      summaryResult,
      surveyResult,
      npsResult,
      gapsResult,
      negFeedbackResult,
      deflectionResult,
    ] = await Promise.all([

      // 1. Conversation thumbs-up metrics
      pool.query(`
        SELECT
          COUNT(*)                                                   AS total,
          COUNT(*) FILTER (WHERE was_helpful = true)                AS positive,
          COUNT(*) FILTER (WHERE was_helpful = false)               AS negative
        FROM chat_conversations
        WHERE created_at >= $1 AND created_at < $2`,
        [weekStart, weekEnd]
      ),

      // 2. Survey metrics (star rating, solved rate)
      pool.query(`
        SELECT
          ROUND(AVG(rating)::numeric, 2)           AS avg_star_rating,
          COUNT(*) FILTER (WHERE solved = true)    AS solved_count,
          COUNT(*) FILTER (WHERE solved IS NOT NULL) AS solved_answers,
          ROUND(AVG(nps_score)::numeric, 2)        AS avg_nps
        FROM conversation_feedback
        WHERE created_at >= $1 AND created_at < $2`,
        [weekStart, weekEnd]
      ),

      // 3. NPS breakdown
      pool.query(`
        SELECT
          COUNT(*) FILTER (WHERE nps_category = 'promoter')  AS promoters,
          COUNT(*) FILTER (WHERE nps_category = 'detractor') AS detractors,
          COUNT(*) FILTER (WHERE nps_score IS NOT NULL)       AS total
        FROM conversation_feedback
        WHERE created_at >= $1 AND created_at < $2`,
        [weekStart, weekEnd]
      ),

      // 4. Top knowledge gaps (unsolved)
      pool.query(`
        SELECT query_text, occurrence_count, thumbs_down_count, low_confidence_count
        FROM chat_knowledge_gaps
        WHERE last_seen >= $1 AND resolved = false
        ORDER BY (thumbs_down_count * 3 + low_confidence_count * 2 + occurrence_count) DESC
        LIMIT 20`,
        [weekStart]
      ),

      // 5. Negative feedback breakdown by reason
      pool.query(`
        SELECT failure_reason, COUNT(*) AS count
        FROM chat_message_feedback
        WHERE rating = 'negative'
          AND created_at >= $1 AND created_at < $2
          AND failure_reason IS NOT NULL
        GROUP BY failure_reason
        ORDER BY count DESC`,
        [weekStart, weekEnd]
      ),

      // 6. Ticket deflection
      pool.query(`
        SELECT
          COUNT(*) FILTER (WHERE action = 'shown')            AS shown,
          COUNT(*) FILTER (WHERE action = 'ticket_cancelled') AS cancelled
        FROM chat_article_suggestion_events
        WHERE created_at >= $1 AND created_at < $2`,
        [weekStart, weekEnd]
      ),
    ]);

    const summary     = summaryResult.rows[0]     || {};
    const survey      = surveyResult.rows[0]       || {};
    const nps         = npsResult.rows[0]           || {};
    const deflection  = deflectionResult.rows[0]    || {};

    const total       = parseInt(summary.total    || 0);
    const positive    = parseInt(summary.positive || 0);
    const negative    = parseInt(summary.negative || 0);
    const rated       = positive + negative;
    const thumbsUpRate = rated > 0 ? Math.round(positive / rated * 100) : null;

    const solvedCount   = parseInt(survey.solved_count    || 0);
    const solvedAnswers = parseInt(survey.solved_answers  || 0);
    const solvedRate    = solvedAnswers > 0 ? Math.round(solvedCount / solvedAnswers * 100) : null;

    const promoters  = parseInt(nps.promoters  || 0);
    const detractors = parseInt(nps.detractors || 0);
    const npsTotal   = parseInt(nps.total      || 0);
    const npsScore   = npsTotal > 0
      ? Math.round((promoters - detractors) / npsTotal * 100)
      : null;

    const shown     = parseInt(deflection.shown     || 0);
    const cancelled = parseInt(deflection.cancelled || 0);
    const deflectionRate = shown > 0 ? Math.round(cancelled / shown * 100) : 0;

    // ── Build alerts ────────────────────────────────────────────────────────
    const alerts = [];
    if (thumbsUpRate !== null && thumbsUpRate < QUALITY_ALERT_THRESHOLD) {
      alerts.push(
        `Thumbs-up rate dropped to <b>${thumbsUpRate}%</b> (threshold: ${QUALITY_ALERT_THRESHOLD}%). Investigate prompt effectiveness and KB coverage.`
      );
    }
    if (gapsResult.rows.length >= 15) {
      alerts.push(
        `<b>${gapsResult.rows.length}</b> unresolved knowledge gaps detected. Consider creating new KB articles.`
      );
    }

    const metrics = {
      totalConversations: total,
      thumbsUpRate,
      avgStarRating:  survey.avg_star_rating ? parseFloat(survey.avg_star_rating) : null,
      npsScore,
      solvedRate,
      deflectionRate,
    };

    // ── Persist snapshot ────────────────────────────────────────────────────
    await pool.query(
      `INSERT INTO chat_quality_snapshots
         (period_start, period_end, total_conversations, thumbs_up_count, thumbs_down_count,
          thumbs_up_rate, avg_star_rating, nps_score, solved_rate, ticket_deflection_rate,
          top_knowledge_gaps, low_rated_intents)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
       ON CONFLICT (period_start, period_end) DO UPDATE SET
         total_conversations    = EXCLUDED.total_conversations,
         thumbs_up_count        = EXCLUDED.thumbs_up_count,
         thumbs_down_count      = EXCLUDED.thumbs_down_count,
         thumbs_up_rate         = EXCLUDED.thumbs_up_rate,
         avg_star_rating        = EXCLUDED.avg_star_rating,
         nps_score              = EXCLUDED.nps_score,
         solved_rate            = EXCLUDED.solved_rate,
         ticket_deflection_rate = EXCLUDED.ticket_deflection_rate,
         top_knowledge_gaps     = EXCLUDED.top_knowledge_gaps,
         low_rated_intents      = EXCLUDED.low_rated_intents,
         report_generated_at    = NOW()`,
      [
        fmtDate(weekStart),
        fmtDate(weekEnd),
        total,
        positive,
        negative,
        thumbsUpRate,
        survey.avg_star_rating ?? null,
        npsScore,
        solvedRate,
        deflectionRate,
        JSON.stringify(gapsResult.rows.slice(0, 10)),
        JSON.stringify(negFeedbackResult.rows),
      ]
    );

    // ── GDPR 90-day purge ───────────────────────────────────────────────────
    pool.query(`SELECT purge_old_chat_data()`).catch(err =>
      console.warn('[ChatQualityJob] GDPR purge error:', err.message)
    );

    // ── Email report ────────────────────────────────────────────────────────
    await sendQualityReport({
      weekStart: fmtDate(weekStart),
      weekEnd:   fmtDate(weekEnd),
      metrics,
      topGaps:         gapsResult.rows,
      lowRatedIntents: negFeedbackResult.rows,
      alerts,
    });

    // Update emailed_at timestamp
    await pool.query(
      `UPDATE chat_quality_snapshots
         SET emailed_at = NOW()
       WHERE period_start = $1 AND period_end = $2`,
      [fmtDate(weekStart), fmtDate(weekEnd)]
    ).catch(() => {});

    const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
    console.log(`✅ [ChatQualityJob] Analysis complete in ${elapsed}s. Conversations: ${total}, Thumbs-up: ${thumbsUpRate ?? 'N/A'}%`);

  } catch (error) {
    console.error('❌ [ChatQualityJob] Analysis failed:', error);
  }
}

// ── Export ────────────────────────────────────────────────────────────────────

/**
 * Start the weekly chat quality analysis job.
 * Schedule: Every Monday at 02:00 AM local time.
 */
export function startChatQualityJob() {
  console.log('📊 [ChatQualityJob] Scheduling weekly quality analysis (Mon 02:00 AM)...');

  // '0 2 * * 1'  →  minute=0, hour=2, any day of month, any month, Monday
  cron.schedule('0 2 * * 1', runWeeklyAnalysis, {
    timezone: 'America/New_York',
  });

  console.log('📊 [ChatQualityJob] Scheduled successfully.');
}

/**
 * Trigger analysis immediately (for manual testing or first-run).
 */
export { runWeeklyAnalysis as runChatQualityAnalysisNow };
